# Generated by Django 5.1.7 on 2025-06-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_mails_verified',
            new_name='is_email_verified',
        ),
    ]
