# Generated by Django 5.1.7 on 2025-07-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_paid',
            new_name='is_expired',
        ),
    ]
