# Generated by Django 5.1.7 on 2025-07-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_paid_cart_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='is_expired',
            new_name='is_paid',
        ),
    ]
